version: '3'
services:
  qiot-edge-service-P-01:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-P-01"
    restart: "no"
    networks:
      - edge
    ports:
      - "8091:8080"
    volumes:
      - qiot-edge-service-P-01-storage:/var/data/qiot/
    environment:
      STATIONSERIAL: "test-station-serialP01"
      STATIONNAME: "test-station-P01"
      STATIONADDRESS: "viale john fitzgerald kennedy 2/D vibo valentia"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "http://registration-service-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com/"
      MQTTURL: "endpoint-service-mqtts-0-svc-rte-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com"
      MQTTPORT: "443"
  qiot-edge-service-P-02:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-P-02"
    restart: "no"
    networks:
      - edge
    ports:
      - "8092:8080"
    volumes:
      - qiot-edge-service-P-02-storage:/var/data/qiot/
    environment:
      STATIONSERIAL: "test-station-serialP02"
      STATIONNAME: "test-station-P02"
      STATIONADDRESS: "soriano calabro"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "http://registration-service-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com/"
      MQTTURL: "endpoint-service-mqtts-0-svc-rte-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com"
      MQTTPORT: "443"
  qiot-edge-service-P-03:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-P-03"
    restart: "no"
    networks:
      - edge
    ports:
      - "8093:8080"
    volumes:
      - qiot-edge-service-P-03-storage:/var/data/qiot/
    environment:
      STATIONSERIAL: "test-station-serialP03"
      STATIONNAME: "test-station-P03"
      STATIONADDRESS: "minsk"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "http://registration-service-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com/"
      MQTTURL: "endpoint-service-mqtts-0-svc-rte-qiotcovid19v2.apps.cluster-fcd8.fcd8.example.opentlc.com"
      MQTTPORT: "443"
volumes:
  qiot-edge-service-P-01-storage:
  qiot-edge-service-P-02-storage:
  qiot-edge-service-P-03-storage:
networks:
  edge:
    external: true
