version: '3'
services:
  edge-service-prod-01:
    image: quay.io/qiotcovid19/edge-service:1.2.0
    container_name: "edge-service-prod-01"
    restart: "no"
    ports:
      - "8091:8080"
    environment:
      STATIONSERIAL: "teststationserial01"
      STATIONNAME: "teststation01"
      STATIONADDRESS: "viale john fitzgerald kennedy 2/D vibo valentia"
      SENSORSURL: "http://edge-sensors:5000/"
      #DATAHUBURL: "http://datahub-registration:5016/"
      #MQTTHOST: "activemq"
      #ENABLESSL: "false"
      #MQTTPORT: "1883"
  edge-service-prod-02:
    image: quay.io/qiotcovid19/edge-service:1.2.0
    container_name: "edge-service-prod-02"
    restart: "no"
    ports:
      - "8092:8080"
    environment:
      STATIONSERIAL: "teststationserial02"
      STATIONNAME: "teststation02"
      STATIONADDRESS: "soriano calabro"
      SENSORSURL: "http://edge-sensors:5000/"
      #DATAHUBURL: "http://datahub-registration:5016/"
      #MQTTHOST: "activemq"
      #ENABLESSL: "false"
      #MQTTPORT: "1883"
  edge-service-prod-03:
    image: quay.io/qiotcovid19/edge-service:1.2.0
    container_name: "edge-service-prod-03"
    restart: "no"
    ports:
      - "8093:8080"
    environment:
      STATIONSERIAL: "teststationserial03"
      STATIONNAME: "teststation03"
      STATIONADDRESS: "minsk"
      SENSORSURL: "http://edge-sensors:5000/"
      #DATAHUBURL: "http://datahub-registration:5016/"
      #MQTTHOST: "activemq"
      #ENABLESSL: "false"
      #MQTTPORT: "1883"
networks:
  default:
    external:
      name: edge