version: "2"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=qiot
      #- MONGO_INITDB_ROOT_USERNAME: root
      #- MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017-27019:27017-27019
    volumes:
      #- ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./volumes/mongo:/data/db
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_PORT: "27017"
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      #ME_CONFIG_MONGODB_AUTH_DATABASE: "qiot"
      #ME_CONFIG_MONGODB_AUTH_USERNAME: "qiot"
      #ME_CONFIG_MONGODB_AUTH_PASSWORD: "qiot"
    ports:
      - 8081:8081
    
volumes:
  db-data:
networks:
  default:
    external:
      name: qiot