apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: qiotcovid19
    user: qiot
    password: qiotcovid19
    url: http://influxdb:8086
    isDefault: true
    editable: true
