version: '3'
services:
  qiot-edge-service-01:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-01"
    restart: "no"
    networks:
      - edge
      - qiotconnect
    ports:
      - "8191:8080"
    volumes:
      - device1-storage:/var/data/qiot/
    environment:
      QUARKUS_PROFILE: "staging"
      STATIONSERIAL: "teststationserialS01"
      STATIONNAME: "teststationS01"
      STATIONADDRESS: "viale john fitzgerald kennedy 2/D vibo valentia"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "https://qiot-datahub-registration-service:8443/"
      MQTTURL: "mosquitto"
      ENABLESSL: "false"
      MQTTPORT: "1883"
      LOGLEVEL: "INFO"

  qiot-edge-service-02:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-02"
    restart: "no"
    networks:
      - edge
      - qiotconnect
    ports:
      - "8192:8080"
    volumes:
      - device2-storage:/var/data/qiot/
    environment:
      QUARKUS_PROFILE: "staging"
      STATIONSERIAL: "teststationserialS02"
      STATIONNAME: "teststationS02"
      STATIONADDRESS: "soriano calabro"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "https://qiot-datahub-registration-service:8443/"
      MQTTURL: "mosquitto"
      ENABLESSL: "false"
      MQTTPORT: "1883"
      LOGLEVEL: "INFO"

  qiot-edge-service-03:
    image: quay.io/qiotcovid19/edge-service:2.0.0-alpha-x86_64
    container_name: "qiot-edge-service-03"
    restart: "no"
    networks:
      - edge
      - qiotconnect
    ports:
      - "8193:8080"
    volumes:
      - device3-storage:/var/data/qiot/
    environment:
      QUARKUS_PROFILE: "staging"
      STATIONSERIAL: "teststationserialS03"
      STATIONNAME: "teststationS03"
      STATIONADDRESS: "minsk"
      SENSORSURL: "http://qiot-edge-sensors:5000/"
      REGISTRATION-SERVICE-URL: "https://qiot-datahub-registration-service:8443/"
      MQTTURL: "mosquitto"
      ENABLESSL: "false"
      MQTTPORT: "1883"
      LOGLEVEL: "INFO"

volumes:
  device1-storage:
  device2-storage:
  device3-storage:
networks:
  edge:
    external: true
  qiotconnect:
    external: true