version: '3'
services:
  activemq:
    image: vromero/activemq-artemis:2-alpine-latest
    container_name: "activemq"
    restart: "always"
    networks:
      - datahub
      - qiotconnect
    ports:
      - "8161:8161"
#      - "61616:61616"
#      - "5672:5672"
      - "1883:1883"
    environment:
      ARTEMIS_USERNAME: "quarkus"
      ARTEMIS_PASSWORD: "quarkus"

  kafka:
    image: obsidiandynamics/kafka
    container_name: "kafka"
    restart: "always"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  mysql:
    image: "mysql"
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qiot"
      MYSQL_DATABASE: "qiot"
      MYSQL_USER: "qiot"
      MYSQL_PASSWORD: "qiot"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-storage:/var/lib/mysql
      
  influxdb:
    image: "quay.io/influxdb/influxdb:v2.0.3"
    container_name: "influxdb"
    ports:
      - "8086:8086"
      - "9999:9999"
    volumes:
      - influxdb-storage:/root/.influxdbv2
    environment:
      INFLUXDB_DB: "qiot"
      INFLUXDB_ADMIN_USER: "qiot"
      INFLUXDB_ADMIN_PASSWORD: "qiot"
  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: "qiot"
      GF_SECURITY_ADMIN_PASSWORD: "qiot"
      
volumes:
  influxdb-storage:
  grafana-storage:
  mysql-storage:
#  mongodb-storage:
#  postgres-storage:
networks:
  datahub:
    external: true
  qiotconnect:
    external: true
  default:
    external:
      name: datahub