version: '3'
services:
  edge-service:
    image: quay.io/qiot/qiot-service
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SENSORSURL: "http://edge-sensors:5000/"
      DATAHUBURL: "http://endpoint-registration:5016/"
      MQTTHOST: "activemq"
networks:
  default:
    external:
      name: qiot