version: '3'
services:
  localization-service:
    image: quay.io/qiotcovid19/qiot-datahub-localization:1.0.0-alpha
    container_name: "localization-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"

  station-service:
    image: quay.io/qiotcovid19/qiot-datahub-station:1.0.0-alpha
    container_name: "station-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"
    environment:
      DBHOST: "mysql"
      LOCALIZATION-SERVICE-URL: "http://localization-service:8080"

  registration-service:
    image: quay.io/qiotcovid19/qiot-datahub-registration:2.0.0-alpha
    container_name: "registration-service"
    restart: "always"
    networks:
      - datahub
      - qiotconnect
    expose:
      - "8080"
    ports:
      - "10001:8080"
    environment:
      STATION-SERVICE-URL: "http://station-service:8080"
      CERTLOCAL: "true"
      LOGLEVEL: "FINE"
      
  gas-collector:
    image: quay.io/qiotcovid19/qiot-datahub-collector-gas:1.0.0-alpha
    container_name: "gas-collector"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      AMQPHOST: "activemq"
      MQTTHOST: "activemq"
  pollution-collector:
    image: quay.io/qiotcovid19/qiot-datahub-collector-pollution:1.0.0-alpha
    container_name: "pollution-collector"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      AMQPHOST: "activemq"
      MQTTHOST: "activemq"

#  datahub-aggregation:
#    image: quay.io/qiotcovid19/qiot-datahub-aggregation:1.0.1
#    container_name: "datahub-aggregation"
#    restart: "always"
#    ports:
#      - "5018:5018"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      HTTPPORT: "5018"
#      MONGODBURL: "mongo:27017"
#  datahub-query:
#    image: quay.io/qiotcovid19/qiot-datahub-query:1.0.1
#    container_name: "datahub-query"
#    restart: "always"
#    ports:
#      - "5200:5200"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      HTTPPORT: "5200"
#      MONGODBURL: "mongo:27017"
#  endpoint-mqtt:
#    image: quay.io/qiotcovid19/qiot-datahub-endpoint-mqtt:1.0.1
#    container_name: "datahub-endpoint-mqtt"
#    restart: "always"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      AMQPHOST: "activemq"
#      MQTTHOST: "activemq"

#  gasstorer:
#    image: quay.io/qiotcovid19/qiot-datahub-storer-gas:1.0.1
#    container_name: "datahub-storer-gas"
#    restart: "always"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      KAFKABOOTSTRAPURL: "kafka:9092"
#      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
#      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
#      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
#      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
#      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
#  pollutionstorer:
#    image: quay.io/qiotcovid19/qiot-datahub-storer-pollution:1.0.1
#    container_name: "datahub-storer-pollution"
#    restart: "always"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      KAFKABOOTSTRAPURL: "kafka:9092"
#      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
#      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
#      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
#      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
#      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
networks:
  datahub:
    external: true
  qiotconnect:
    external: true
  default:
    external:
      name: datahub