version: '3'
services:
  datahub-registration:
    image: quay.io/qiotcovid19/qiot-datahub-registration:1.0.1
    container_name: "datahub-registration"
    restart: "no"
    networks:
      - datahub
      - qiotconnect
    ports:
      - "5016:5016"
    environment:
      QUARKUS_PROFILE: "staging"
      HTTPPORT: "5016"
      MONGODBURL: "mongo:27017"
  datahub-aggregation:
    image: quay.io/qiotcovid19/qiot-datahub-aggregation:1.0.1
    container_name: "datahub-aggregation"
    restart: "no"
    ports:
      - "5018:5018"
    environment:
      QUARKUS_PROFILE: "staging"
      HTTPPORT: "5018"
      MONGODBURL: "mongo:27017"
  datahub-query:
    image: quay.io/qiotcovid19/qiot-datahub-query:1.0.1
    container_name: "datahub-query"
    restart: "no"
    ports:
      - "5200:5200"
    environment:
      QUARKUS_PROFILE: "staging"
      HTTPPORT: "5200"
      MONGODBURL: "mongo:27017"
  endpoint-mqtt:
    image: quay.io/qiotcovid19/qiot-datahub-endpoint-mqtt:1.0.1
    container_name: "datahub-endpoint-mqtt"
    restart: "no"
    environment:
      QUARKUS_PROFILE: "staging"
      AMQPHOST: "activemq"
      MQTTHOST: "activemq"
  gasstorer:
    image: quay.io/qiotcovid19/qiot-datahub-storer-gas:1.0.1
    container_name: "datahub-storer-gas"
    restart: "no"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      MONGODBURL: "mongo:27017"
  pollutionstorer:
    image: quay.io/qiotcovid19/qiot-datahub-storer-pollution:1.0.1
    container_name: "datahub-storer-pollution"
    restart: "no"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      MONGODBURL: "mongo:27017"
networks:
  datahub:
    external: true
  qiotconnect:
    external: true
  default:
    external:
      name: datahub