version: '3'
services:
  qiot-datahub-import-service:
    image: quay.io/qiotcovid19/qiot-datahub-importer:2.0.0-beta
    container_name: "qiot-datahub-import-service"
    restart: "always"
    networks:
      - datahub
    ports:
      - "5100:8080"
    environment:
      QUARKUS_PROFILE: "staging"
      DBHOST: "postgresql"
      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
      
  qiot-datahub-localization-service:
    image: quay.io/qiotcovid19/qiot-datahub-localization:1.0.0-alpha
    container_name: "qiot-datahub-localization-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"
    environment:
      QUARKUS_PROFILE: "staging"
      LOGLEVEL: "FINE"

  qiot-datahub-station-service:
    image: quay.io/qiotcovid19/qiot-datahub-station:1.0.0-alpha
    container_name: "qiot-datahub-station-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"
    environment:
      QUARKUS_PROFILE: "staging"
      DBHOST: "postgresql"
      LOCALIZATION-SERVICE-URL: "http://qiot-datahub-localization-service:8080"

  qiot-datahub-registration-service:
    image: quay.io/qiotcovid19/qiot-datahub-registration:2.0.0-alpha
    container_name: "qiot-datahub-registration-service"
    restart: "always"
    networks:
      - datahub
      - qiotconnect
    expose:
      - "8080"
    ports:
      - "8443:8443"
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      CERT_MANAGER_ENABLED: "false"
      LOGLEVEL: "FINE"
      
  qiot-datahub-gas-collector-service:
    image: quay.io/qiotcovid19/qiot-datahub-collector-gas:1.0.0-alpha
    container_name: "qiot-datahub-gas-collector-service"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      MQTTHOST: "mosquitto"
  qiot-datahub-pollution-collector-service:
    image: quay.io/qiotcovid19/qiot-datahub-collector-pollution:1.0.0-alpha
    container_name: "qiot-datahub-pollution-collector-service"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      MQTTHOST: "mosquitto"

  qiot-datahub-gas-storer-service:
    image: quay.io/qiotcovid19/qiot-datahub-storer-gas:2.0.0-alpha
    container_name: "qiot-datahub-gas-storer-service"
    restart: "always"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
  qiot-datahub-pollution-storer-service:
    image: quay.io/qiotcovid19/qiot-datahub-storer-pollution:2.0.0-alpha
    container_name: "qiot-datahub-pollution-storer-service"
    restart: "always"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
networks:
  datahub:
    external: true
  qiotconnect:
    external: true
  default:
    external:
      name: datahub