version: '3'
services:
  qiot-datahub-localization-service:
    image: quay.io/qiotcovid19/qiot-datahub-localization:1.0.0-alpha
    container_name: "qiot-datahub-localization-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"
    environment:
      QUARKUS_PROFILE: "staging"

  qiot-datahub-station-service:
    image: quay.io/qiotcovid19/qiot-datahub-station:1.0.0-alpha
    container_name: "qiot-datahub-station-service"
    restart: "always"
    networks:
      - datahub
    expose:
      - "8080"
    environment:
      QUARKUS_PROFILE: "staging"
      DBHOST: "mysql"
      LOCALIZATION-SERVICE-URL: "http://qiot-datahub-localization-service:8080"

  qiot-datahub-registration-service:
    image: quay.io/qiotcovid19/qiot-datahub-registration:2.0.0-alpha
    container_name: "qiot-datahub-registration-service"
    restart: "always"
    networks:
      - datahub
      - qiotconnect
    expose:
      - "8080"
    ports:
      - "10001:8080"
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      CERTLOCAL: "true"
      LOGLEVEL: "FINE"
      
  qiot-datahub-gas-collector-service:
    image: quay.io/qiotcovid19/qiot-datahub-collector-gas:1.0.0-alpha
    container_name: "qiot-datahub-gas-collector-service"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      AMQPHOST: "activemq"
      MQTTHOST: "activemq"
  qiot-datahub-pollution-collector-service:
    image: quay.io/qiotcovid19/qiot-datahub-collector-pollution:1.0.0-alpha
    container_name: "qiot-datahub-pollution-collector-service"
    restart: "always"
    networks:
      - datahub
    environment:
      QUARKUS_PROFILE: "staging"
      STATION-SERVICE-URL: "http://qiot-datahub-station-service:8080"
      AMQPHOST: "activemq"
      MQTTHOST: "activemq"

#  datahub-aggregation:
#    image: quay.io/qiotcovid19/qiot-datahub-aggregation:1.0.1
#    container_name: "datahub-aggregation"
#    restart: "always"
#    ports:
#      - "5018:5018"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      HTTPPORT: "5018"
#      MONGODBURL: "mongo:27017"
#  datahub-query:
#    image: quay.io/qiotcovid19/qiot-datahub-query:1.0.1
#    container_name: "datahub-query"
#    restart: "always"
#    ports:
#      - "5200:5200"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      HTTPPORT: "5200"
#      MONGODBURL: "mongo:27017"
#  endpoint-mqtt:
#    image: quay.io/qiotcovid19/qiot-datahub-endpoint-mqtt:1.0.1
#    container_name: "datahub-endpoint-mqtt"
#    restart: "always"
#    environment:
#      QUARKUS_PROFILE: "staging"
#      AMQPHOST: "activemq"
#      MQTTHOST: "activemq"

  qiot-datahub-gas-storer-service:
    image: quay.io/qiotcovid19/qiot-datahub-storer-gas:2.0.0-alpha
    container_name: "datahub-storer-gas"
    restart: "always"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
  qiot-datahub-pollution-storer-service:
    image: quay.io/qiotcovid19/qiot-datahub-storer-pollution:2.0.0-alpha
    container_name: "datahub-storer-pollution"
    restart: "always"
    environment:
      QUARKUS_PROFILE: "staging"
      KAFKABOOTSTRAPURL: "kafka:9092"
      INFLUXDB_CONNECTION_STRING: "http://influxdb:8086"
      INFLUXDB_TOKEN: "hBta3AUlJMCb7y4qpG4o1LNGR6CQpbgJi88NYMX2ta8zj5Xi_EBIezhgtPcYNTXhnbKfgcpUbHDgnArIEKxFxA=="
      INFLUXDB_ORG_ID: "08ebf5cf8aef6f0b"
      INFLUXDB_DATA_BUCKET_ID: "f073a47029310613"
      INFLUXDB_DATA_BUCKET_NAME: "qiotcovid19"
networks:
  datahub:
    external: true
  qiotconnect:
    external: true
  default:
    external:
      name: datahub